### ISSUE TITLE
registration form broken

### ISSUE THREAD

**Issue by maggie-j-liu** [hyphen-hacks/website#1]
hi! maybe it's not finished yet, but i get this when i try to register 
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/63619830/216413812-c793ece6-d7f1-4ef0-9f32-9fed1664538d.png">

if it's still in progress, using this issue as a way to track when i can register :D

**Comment by tandpfun** [comment]
Hi! So sorry about that, I accidentally pushed a bug. You should be able to apply now!

**Comment by maggie-j-liu** [comment]
thank you! works now :D
